---
- hosts: dell-switchOS9
  connection: local
  vars_files:
    - /path/to/vault/file.yml

  tasks:
  - name: show run
    dellos9_command:
      commands:
        - show run | ex username
      provider: "{{ cli }}"
    register: config

  - name: save output to /backups
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "/path/to/output/folder/file.txt"
      backup: yes